### ISSUE TITLE
Not available in the latest paper

### ISSUE THREAD

**Issue by gary81013** [PyvesB/AntiWorldFly#38]
Plugin Version: AntiWorldFly-2.5.1

Minecraft Version: paper-1.19.3#431

Spigot/CraftBukkit version: 

Other Plugins you are using: 

## Steps to Reproduce

[02:40:11 INFO]: [AntiWorldFly] Enabling AntiWorldFly v2.5.1
[02:40:11 INFO]: [AntiWorldFly] Registering listeners...
[02:40:11 ERROR]: Error occurred while enabling AntiWorldFly v2.5.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "listener" is null
        at io.papermc.paper.plugin.manager.PaperEventManager.createRegisteredListeners(PaperEventManager.java:136) ~[paper-1.19.3.jar:git-Paper-431]
        at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:83) ~[paper-1.19.3.jar:git-Paper-431]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:131) ~[paper-1.19.3.jar:git-Paper-431]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:670) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.hm.antiworldfly.AntiWorldFly.onEnable(AntiWorldFly.java:147) ~[AntiWorldFly-2.5.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-431]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-431]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-431]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-431]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:40:11 INFO]: [AntiWorldFly] Disabling AntiWorldFly v2.5.1
[02:40:11 INFO]: [AntiWorldFly] AntiWorldFly has been disabled.

**Comment by Sidpatchy** [comment]
Looks to be an issue with the plugin's logic for detecting WorldGuard. There should be a patch out within the hour.

**Comment by Sidpatchy** [comment]
Update pending on dev.bukkit, but should be live everywhere else. Thanks for the report!

**Comment by gary81013** [comment]
Thanks
