### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by JustinBery** [PyvesB/AntiWorldFly#39]
Could not pass event PlayerCommandPreprocessEvent to AntiWorldFly v2.5.2
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because the return value of "com.hm.antiworldfly.AntiWorldFly.getOtherBlockedCommands()" is null
        at com.hm.antiworldfly.listener.CommandPreProcess.onPlayerCommandPreprocessEvent(CommandPreProcess.java:61) ~[AntiWorldFly-2.5.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor612.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.dispatchCommand(BukkitCommandSender.kt:50) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitCommandSender.performCommand(BukkitCommandSender.kt:40) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer.performCommand(BukkitPlayer.kt:446) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command$onExecute$1.invoke(Command.kt:24) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command$onExecute$1.invoke(Command.kt:26) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.send.Command.onExecute(Command.kt:28) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:93) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:91) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$7.run(BukkitExecutor.kt:98) ~[TrMenu-3.1.17.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]

**Comment by Sidpatchy** [comment]
I'm not able to reproduce this error without any steps to reproduce, or any info on what is being done to cause it.
At a bare minimum, when you're asking for help, **PLEASE** use the issue template.

```<!--- DO NOT DELETE/IGNORE THIS TEMPLATE, DOING SO WILL RESULT IN NO SUPPORT! --->``` this is the first and last line of the issue template that you deleted.

Please provide me the following:
1. A copy of your config.yml file (use GitHub gist or some similar pastebin service)
2. What you are doing to create this error message. I can see that a command is likely being run, but I have absolutely no context.
3. I'm not sure what TrMenu is, but it's possible that it's somehow interfering with AWF and causing the error. To rule out this possibility, you could try disabling TrMenu temporarily and see if the error still occurs. If the error goes away, then it's likely that there is some conflict between the two plugins that needs to be resolved. Please let me know the results of this test, if it is the cause, I will have to look into it further.

**Comment by Sidpatchy** [comment]
Given no response I'm going to close this.
