### ISSUE TITLE
PlayerChangeWorld Error

### ISSUE THREAD

**Issue by QuickGlare** [PyvesB/AntiWorldFly#8]
When a player change world in my server, i see this error: 

`[10:24:09 ERROR]: Could not pass event PlayerChangedWorldEvent to AntiWorldFly v2.2.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-36]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-36]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-36]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.PlayerList.moveToWorld(PlayerList.java:622) [PaperSpigot.jar:git-PaperSpigot-36]
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:526) [PaperSpigot.jar:git-PaperSpigot-36]
        at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials.jar:?]
        at com.earth2me.essentials.Teleport.warp(Teleport.java:263) [Essentials.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:130) [Essentials.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51) [Essentials.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PaperSpigot.jar:git-PaperSpigot-36]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [PaperSpigot.jar:git-PaperSpigot-36]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:766) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1044) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:881) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:789) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [PaperSpigot.jar:git-PaperSpigot-36]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot.jar:git-PaperSpigot-36]
Caused by: java.lang.NoSuchFieldError: SPECTATOR
        at com.hm.antiworldfly.listener.AntiWorldFlyWorldJoin.worldJoin(AntiWorldFlyWorldJoin.java:32) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot.jar:git-PaperSpigot-36]
        ... 27 more`

i use 1.7.10

**Comment by PyvesB** [comment]
Hello QuickGlare,

Sorry about that. Will be releasing a new version soon. ;-)

Cheers,

Pyves
